const questions = [
  'What inspired you to pursue a career in tech, and how did you get started?',
  'As a beginner developer, what do you find most challenging about learning to code, and how do you overcome these challenges?',
  'What are your favorite programming languages and tools, and what do you enjoy most about working with them?',
  'Have you ever experienced imposter syndrome as a developer, and if so, how have you dealt with it?',
  "What are some common interview questions you've encountered in tech interviews, and how do you prepare for them?",
  'How do you stay motivated and focused while learning to code, especially when faced with difficult concepts or challenges?',
  "What advice would you give to someone who is considering a career in tech, but isn't sure where to start?",
  'How do you balance learning new technologies and improving your existing skills, while also keeping up with your other responsibilities and commitments?',
  "What are some of the most interesting or innovative tech projects you've worked on, and what did you learn from them?",
  'How do you stay up-to-date with the latest developments and trends in the tech industry, and what resources do you rely on for information and inspiration?',
  'What are some common career paths in tech, and which ones are you most interested in pursuing?',
  'How do you network and build professional relationships in the tech industry, especially as a beginner?',
  'What are some important skills and qualities that are valued by tech employers, and how do you develop them?',
  'How do you negotiate salary and benefits when starting a new job in tech?',
  'What are some ways to advance your career in tech, such as getting certifications or going back to school?',
  'What are some good resources for learning to code, such as books, websites, or online courses?',
  'How do you decide which programming language to learn first, and why?',
  'What are some common mistakes that beginners make when learning to code, and how can they be avoided?',
  'How do you set realistic goals and measure your progress when learning to code?',
  'What are some good strategies for practicing coding and getting feedback on your work?',
  'What are some pros and cons of different programming languages and tools, and how do you choose which ones to use for a particular project?',
  "What are some up-and-coming programming languages and tools that you're excited about?",
  'What are some tools and frameworks that have made your development process more efficient and effective?',
  'How do you stay up-to-date with new releases and updates for your favorite programming languages and tools?',
  'What are some common mistakes that developers make when choosing and using programming languages and tools?',
  'What is imposter syndrome, and how does it affect people in the tech industry?',
  'How can you recognize and overcome imposter syndrome, both as an individual and as a community?',
  'What are some common triggers of imposter syndrome, and how can they be addressed?',
  'How do you support others who are struggling with imposter syndrome, especially in a professional context?',
  'What are some effective ways to build self-confidence and resilience in the face of imposter syndrome?',
  'What are some common types of tech interviews, such as technical interviews or behavioral interviews?',
  'How do you prepare for different types of tech interviews, such as researching the company or practicing coding challenges?',
  "What are some common interview questions that you've encountered in tech interviews, and how do you answer them effectively?",
  'What are some strategies for standing out in a crowded field of candidates during a tech interview?',
  'How do you follow up after a tech interview, such as sending a thank-you note or requesting feedback?',
  'What are some different learning styles, and how do they impact your approach to learning programming?',
  'How do you balance structured learning, such as taking classes or following tutorials, with self-directed learning, such as working on personal projects?',
  'What are some effective ways to troubleshoot and debug code when you encounter errors or bugs?',
  'What are some good ways to collaborate with other developers and learn from their perspectives and experiences?',
  'How do you stay motivated and engaged when learning to code, especially when faced with setbacks or challenges?',
  'What are some ethical issues that arise in the tech industry, such as privacy, security, or bias?',
  'What are some good resources for learning about tech ethics, such as books, articles, or organizations?',
  'How can you use your technical skills to create positive social impact, such as through open source projects or volunteering?',
  'What are some advantages and challenges of remote work in the tech industry?',
  'How can you stay productive and motivated when working from home or other remote locations?',
  'What are some effective strategies for communicating and collaborating with remote team members?',
  'How do you maintain work-life balance when working remotely, and avoid burnout?',
  'What are some good tools and technologies for facilitating remote work, such as video conferencing or project management software?',
  'What are some benefits of mentorship in the tech industry, such as learning new skills, gaining career advice, or expanding your professional network?',
  'How do you find a mentor in the tech industry, and what should you look for in a mentor?',
  'What are some effective ways to build a mentoring relationship, such as setting goals, establishing regular check-ins, or providing feedback?',
  'How do you become a mentor yourself, and what are some qualities of effective mentors?',
  'How can mentorship programs and initiatives be improved to better serve underrepresented groups in the tech industry?',
  'What are some challenges and barriers faced by underrepresented groups in the tech industry, such as women, people of color, or LGBTQ+ individuals?',
  'How can tech companies and communities promote diversity and inclusion, such as through hiring practices, training and development programs, or outreach initiatives?',
  'What are some examples of successful diversity and inclusion efforts in the tech industry, and what can we learn from them?',
  'How can individuals and communities advocate for diversity and inclusion in the tech industry, such as through allyship, activism, or education?',
  'How do you cultivate a culture of respect, empathy, and inclusivity in your own tech community or workplace?',
];
