const LEARN_EMOJI_NAME = 'learn-1';
const BUILD_EMOJI_NAME = 'build-1';
const TEACH_EMOJI_NAME = 'teach-1';
const APPROVE_EMOJI = '✅';
const REJECT_EMOJI = '❌';
const EMAIL_SENT_EMOJI = '📨';
const EMAIL_APPROVED_EMOJI = '📧';
const TWITTER_APPROVED_EMOJI = '🐦';

export const EMOJI_NAMES = {
  LEARN_EMOJI_NAME,
  BUILD_EMOJI_NAME,
  TEACH_EMOJI_NAME,
  APPROVE_EMOJI,
  REJECT_EMOJI,
  EMAIL_APPROVED_EMOJI,
  EMAIL_SENT_EMOJI,
  TWITTER_APPROVED_EMOJI,
};

export const kudoEmojis = [
  EMOJI_NAMES.LEARN_EMOJI_NAME,
  EMOJI_NAMES.BUILD_EMOJI_NAME,
  EMOJI_NAMES.TEACH_EMOJI_NAME,
];
